variable "create" {
  type        = bool
  description = "Whether to create the resource"
  default     = true
}

variable "security_group_description" {
  type        = string
  description = "Description for the Security Group"
  default     = "Generated by Terraform"
}

variable "vpc_id" {
  type        = string
  description = "The VPC Id where this resource is created"
  default     = ""
}

variable "enabled_default_egress_rule" {
  type        = bool
  description = "Whether to enabled the default egress rule"
  default     = true
}

variable "security_group_name" {
  type        = string
  description = "The name of this security group"
  default     = ""
}

variable "ingress_rule" {
  type        = any
  description = "The security group ingress rules"
  default     = []
}

variable "egress_rule" {
  type        = any
  description = "The security group ingress rules"
  default     = []
}